### ISSUE TITLE
yanmagajp

### ISSUE THREAD

**Issue by v-mstrs** [oxdz/ccdl#22]
Does not work
![qweqweqweqweqwe](https://user-images.githubusercontent.com/104088833/173198197-2a2462a4-f4d3-4cb8-b367-4f1d50190485.PNG)
.

**Comment by NamesJoeyWheeler** [comment]
Getting a similar error:
```
Traceback (most recent call last):
  File "CcdlSimpleStarter.py", line 93, in <module>
  File "ccdl\yanmaga.py", line 147, in downloader
  File "ccdl\yanmaga.py", line 42, in get_comic_user_and_viewer_id
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by vircoys** [comment]
下载 chromedriver 了么，下载对应浏览器版本的 https://github.com/oxdz/ccdl#install 到程序目录

**Comment by vircoys** [comment]
Have you downloaded chromedriver? Please download the corresponding version of chromedriver for your browser to the program directory.

1. https://googlechromelabs.github.io/chrome-for-testing/#stable
2. http://chromedriver.storage.googleapis.com/index.html
