### ISSUE TITLE
支持 shonenjumpplus magazine

### ISSUE THREAD

**Issue by artsunjai** [oxdz/ccdl#7]
shonenjumpplus 的定期購買 下載失敗，已經有登入帳號購買

**Comment by artsunjai** [comment]
![螢幕擷取畫面 2021-07-21 003036](https://user-images.githubusercontent.com/77482540/126361406-8dc742cc-b9c7-4e51-9428-fbd8d263e107.png)

**Comment by artsunjai** [comment]
![jump](https://user-images.githubusercontent.com/77482540/126368254-4e61e4a7-1192-46e8-9e34-12b62fd686ed.png)
少年jump的定期購下載失敗

**Comment by artsunjai** [comment]
gaugau.futabanet.jp 網也沒辦法用

**Comment by vircoys** [comment]
可能是网站升级导致失效

**Comment by artsunjai** [comment]
一般的episode可以下載，但定期購的magazine不行

**Comment by artsunjai** [comment]
能處理嗎？如果需要我可以提供帳號

**Comment by vircoys** [comment]
看了下链接，ccdl 只支持这种格式的链接： https://shonenjumpplus.com/episode/xxx，

/magazine/xxxx 这种是不支持的

https://github.com/oxdz/ccdl/blob/77db7e7e3732b3a20e58c82a8cc67c717a83d917/src/ccdl/utils.py#L32

**Comment by artsunjai** [comment]
但是提取方法是一樣的，能添加嗎…

**Comment by artsunjai** [comment]
希望能添加

**Comment by artsunjai** [comment]
![螢幕擷取畫面 2022-05-06 172512](https://user-images.githubusercontent.com/77482540/167105172-b3adeb38-e93f-43c4-a30a-e1063951a4d1.png)

**Comment by vircoys** [comment]
图里的是 "ccdl-0.2.11-py3.10"，先 pip 删除旧版的 ccdl 再安装 0.2.13 试试

artsunjai ***@***.***> 于2022年5月6日周五 17:26写道：

**Comment by artsunjai** [comment]
可以了，但是图片画质好像有点问题
![77](https://user-images.githubusercontent.com/77482540/167354046-6628d094-5984-48ae-9b3c-70877026f785.jpg)

左邊是用ccdl 下载的 右邊是用
https://github.com/yujinpan/tampermonkey-extension   网站图片（背景图，svg，canvas）抓取预览下载 

ccdl下载出來的比較光，用PS打开是灰阶

**Comment by eggplants** [comment]
@artsunjai 
Could you try my downloader?
https://github.com/eggplants/getjump
